### PR TITLE
(MODULES-5007) Document support for SSD storage - 1/6

### PR DESCRIPTION
**Pull request by GeoffWilliams**
Exising puppet azure module alreadys supports SSD storage (feature request unnecessary) so I just make the documentation around it a bit clearer.

### CODE REVIEW

**Comment by jorhett** [comment]
@GeoffWilliams you've been doing some great work. I've been doing some other stuff that depends on yours. Want to get together and create a working branch to develop stuff together?

**Comment by GeoffWilliams** [comment]
@jorhett Thanks! It's great to get community feedback on this.  I'm still hopeful of getting this series of PRs merged.  Right now I'm working with another customer but I've been talking to people at puppet and I "just" need to get the beaker tests passing (which I've been working on the last 2/3 weeks on and off - long story short I'm nearly done and should have another PR soon which will should unlock the path to getting these other ones merged). - basically hang fire for the moment but failing that, sure why not

**Comment by jorhett** [comment]
well as soon as your stuff gets merged, I've got a basket full of new types which depend on your changes ;-)  virtual networks, subnets, blob storage, vnet peering, security groups....

**Comment by GeoffWilliams** [comment]
@jorhett Final PR #154 added to fix failing beaker tests - approx 1 month of work - this was what was blocking previous PRs from being merged so :crossed_fingers:

**Pull request merged**
